api_platform:
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    exception_to_status:
        App\Exception\NotFoundException: 404
        App\Exception\UnauthorizedException: 401
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
