name: Code Analysis

on:
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  grumphp:
    name: GrumPHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          working-directory: ./app
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer packages
        working-directory: ./app
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute GrumPHP tasks
        working-directory: ./app
        run: vendor/bin/grumphp run
